In [2]:
#Question 1
res =[]
for i in range(2000, 2300):
    if (i % 7 ==  0) and (i % 5 != 0 ):
        res.append(i)
print(res)


[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296]


In [3]:
#Question 2
x=input(int)
res = 1
if int(x) == 0:
    res = 1
else:
    for i in range(1,int(x)+1):
        res = int(i)*res
print(res)


<class 'int'>5
120


In [4]:
#Question 3
import numpy as np
n = input(int)
dic = dict()

for i in range(1, int(n)+1):
    dic[i]= i*i
print(dic)


<class 'int'>4
{1: 1, 2: 4, 3: 9, 4: 16}


In [6]:
#Question 4
string = input()
n = input()
res=""

for i in range(0, (len(string)-1)):
    if i in range(0,int(n)):
        res = res + string[i]
        
    else:
        res = res + string[i+1]
print(res)


GoMyCode
4
GoMyode


In [7]:
#Question 5
import numpy as np
arr = np.array([[0,1],[2,3],[4,5]])
print("arrray", arr)

listarray = arr.tolist()
print("list of arry: ",listarray)


arrray [[0 1]
 [2 3]
 [4 5]]
list of arry:  [[0, 1], [2, 3], [4, 5]]


In [8]:
#Question 6
import numpy as np
tab1 = np.array([0,1,2])
tab2 = np.array([2,1,0])
mat = np.array([tab1, tab2])
print(mat)
np.cov(mat)


[[0 1 2]
 [2 1 0]]


array([[ 1., -1.],
       [-1.,  1.]])

In [11]:
#Question 7
import math
# [(2 * C * D)/H] 
C = 50
H =30
D = input("siser une séquence des valeurs :")
l = D.split(',')
res = 0
for i in range(0,len(D)):
    if D[i] != ',':
        res =math.sqrt((2*C*int(D[i]))/H)
        print(round(res))


siser une séquence des valeurs :1,2,3,4
2
3
3
4
